###
GET http://localhost:8083/connector-plugins

###
GET http://localhost:8083/connectors

###
POST http://localhost:8083/connectors
Content-Type: application/json

{
  "name": "bloxbean-web3-source-connector-latest-blocks",
  "config": {
    "connector.class": "com.bloxbean.kafka.connectors.web3.BlockSourceConnector",
    "tasks.max": 1,
    "web3_rpc_url": "http://<host>:8545",
    "topic": "aion-latest-blocks",
    "start_block": 0,
    "block_time": 10,
    "no_of_blocks_for_finality": 0
  }
}

###
# Create a new connector instance with finality blocks setting.
POST http://localhost:8083/connectors
Content-Type: application/json

{
  "name": "bloxbean-web3-source-connector",
  "config": {
    "connector.class": "com.bloxbean.kafka.connectors.web3.BlockSourceConnector",
    "tasks.max": 1,
    "web3_rpc_url": "http://<host>:8545",
    "topic": "aion-blocks",
    "start_block": 0,
    "block_time": 10,
    "no_of_blocks_for_finality": 30
  }
}

###
GET http://localhost:8083/connectors/bloxbean-web3-source-connector

###
GET http://localhost:8083/connectors/bloxbean-web3-source-connector/status

###
POST http://localhost:8083/connectors/bloxbean-web3-source-connector/restart

###
PUT http://localhost:8083/connectors/bloxbean-web3-source-connector/pause

###
PUT http://localhost:8083/connectors/bloxbean-web3-source-connector/resume

###
DELETE http://localhost:8083/connectors/<connector_name>

###

